# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 513c2570598af10b86ebc18889f29464b51459899148b48fcb75c3d1ea4c1ce4dc1301917652d050f0232dca45cd0843d83787a2287f66fa70eb22f2d375b2fe

test:
  secret_key_base: aae774316a23691c2c0190c024342dae6658aacb5143353b5e3fdf714a251503fa5f68a7b981277785e941c52114b6972ff7b7c8c97bceb26b723dfd11bbce0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
